#!/bin/bash
# Add the following to crontab -e to run this every ten minutes */10 * * * * /home/alex/sounder/run_analysis >> /home/alex/sounder/analysis.log &
echo "Started run_analysis - tail -f /var/log/syslog for more information"
current_time="`date +%Y/%m/%d_%H:%M`";

export sdir=/home/alex/sounder/analyze_prc.py 
export outdir=/data 
export chan=hfrx_0 
export codelen=1000 
export threshold=0 

# Check output directory size as a function of time
andir=$outdir/prc_analysis/$chan

if [ -d "$andir" ]; then
    sz1=`df $andir |  tail -n1 | awk '{print $3}'`
    sleep 10
    sz2=`df $andir |  tail -n1 | awk '{print $3}'`
else
    sz1="1"
    sz2="1"
fi

# Start the receiver code if the directory is not getting bigger
if [ $sz1 == $sz2 ]; then
    echo "$andir not getting bigger. Launching $sdir at ${current_time}"
    python $sdir $outdir -c $chan -l $codelen -s 0 -t $threshold
else
    echo "prc_analysis already running"
fi
exit 0
