#!/bin/sh
# Add the following to crontab -e to run this every minute * * * * * /home/alex/sounder/run_rx_aoa >> /home/alex/sounder/run_rx_aoa.log &
echo "Started run_rx_aoa - tail -f /var/log/syslog for more information"
current_time="`date +%Y%m%d%H%M`";

export sdir=/home/alex/sounder/odin.py 
export freq_list='freq_lists/antarctic_ops.txt'
export rate=5E5
export type='sc16'

if ! pgrep -x "python" > /dev/null
then
    echo "odin.py not running, launching at ${current_time}"
    
    python $sdir -m 192.168.10.12 -d "A:A A:B" -c hfrx_0,hfrx_1 --type $type -f $freq_list -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.13 -d "A:A A:B" -c hfrx_2,hfrx_3 --type $type -f $freq_list -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.15 -d "A:A A:B" -c hfrx_4,hfrx_5 --type $type -f $freq_list -r $rate -i 10 /data  &
else :
    pid="`pgrep -x python`"
    echo "odin.py running at ${current_time} as pid ${pid}"
fi
exit 0
