#!/bin/sh
# Add the following to crontab -e to run this every minute * * * * * /home/alex/sounder_code/run_rx_aoa >> /home/alex/sounder_code/run_rx_aoa.log &
echo "Started run_rx - tail -f /var/log/syslog for more information"
current_time="`date +%Y%m%d%H%M`";

export sdir=/home/alex/digital_rf-2.6.0b1/tools/thor.py 
export freq=5E6
export rate=1E6

if ! pgrep -x "python" > /dev/null
then
    echo "thor.py not running, launching at ${current_time}"
    
    python $sdir -m 192.168.10.12 -d "A:A" -c hfrx_0 -f $freq -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.12 -d "A:B" -c hfrx_1 -f $freq -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.13 -d "A:A" -c hfrx_2 -f $freq -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.13 -d "A:B" -c hfrx_3 -f $freq -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.15 -d "A:A" -c hfrx_4 -f $freq -r $rate -i 10 /data  &
    python $sdir -m 192.168.10.15 -d "A:B" -c hfrx_5 -f $freq -r $rate -i 10 /data  &
else :
    pid="`pgrep -x python`"
    echo "odin.py running at ${current_time} as pid ${pid}"
fi
exit 0
