#!/bin/sh
# Add the following to crontab -e to run this every minute * * * * * /home/alex/sounder_code/run_tx >> /home/alex/sounder_code/run_tx.log &
echo "Started run_tx - tail -f /var/log/syslog for more information"
current_time="`date +%Y/%m/%d_%H:%M`"

export sdir=/home/alex/sounder/
export tx=$sdir'tx_chirp.py'
export freq_list=$sdir'freq_lists/mcm_ops.flist'
export flog=$sdir'freq_lists/freqstep.log'
export waveform=$sdir'waveforms/code-l1000-b10-000000f.bin'
export rate=5E5
export mboard='192.168.10.3'

if test `find "$flog" -mmin -1`  
then
    pid="`pgrep -x python`"
    echo "tx_chirp.py running at ${current_time} possibly as pid ${pid}"
else :
    echo "tx_chirp.py not running, launching at ${current_time}"
    python $tx -m $mboard -d "A:A" -f $freq_list -G 1 -g 0 -r $rate $waveform
fi
exit 0
